"""Signed entitlement tokens.

The problem this solves: a licence file on the customer's own disk is trivially
editable, so anything that reads one and believes it is not enforcement, it is
decoration. The fix is not obfuscation, which only buys time against anyone who
cares. The fix is that the client cannot mint a valid answer at all.

So the server signs a small payload with an Ed25519 private key it never
shares, and FIRE carries only the public key. Editing the cached file changes
the payload, the signature stops verifying, and the token is discarded. Nobody
can forge one without the private key, and the private key is never on a
customer's machine.

Two deliberate properties:

**An offline grace period.** A trading terminal that locks a paying customer
out because our licence server had a bad afternoon is worse than one that
trusts a recently valid token for a few more days. The token carries its own
grace window and the client honours it.

**No personal data in the token.** It carries a status, a plan name, an expiry,
an opaque install id and the last four characters of the licence key. There is
no email address, no name and no customer id, because the token is written to
disk on a machine we do not control.
"""
from __future__ import annotations

import base64
import json
import time
from dataclasses import dataclass
from typing import Any, Optional

TOKEN_VERSION = 1
DEFAULT_GRACE_DAYS = 7


def _b64e(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _b64d(text: str) -> bytes:
    pad = "=" * (-len(text) % 4)
    return base64.urlsafe_b64decode(text + pad)


@dataclass(frozen=True)
class TokenPayload:
    status: str                  # trial | active | expired | revoked
    expires: Optional[float]
    plan: str = ""
    install: str = ""            # opaque id generated by the client
    key_tail: str = ""           # last four characters, for display only
    issued: float = 0.0
    grace_days: int = DEFAULT_GRACE_DAYS
    max_version: Optional[str] = None

    def as_dict(self) -> dict[str, Any]:
        return {"v": TOKEN_VERSION, "status": self.status,
                "expires": self.expires, "plan": self.plan,
                "install": self.install, "key_tail": self.key_tail,
                "issued": self.issued, "grace_days": self.grace_days,
                "max_version": self.max_version}

    @property
    def grace_expires(self) -> float:
        """When a cached token stops being trusted with no fresh check."""
        return self.issued + self.grace_days * 86400


def load_public_key(material: bytes):
    """Accept a raw 32 byte Ed25519 public key, its base64 form, or a PEM.

    The raw form is what the application actually carries. A PEM public key
    would put a BEGIN block inside the source tree, and the guard that keeps
    key material out of `src/fire` is worth more than the convenience.
    """
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

    if isinstance(material, str):
        material = material.encode("ascii")
    if b"BEGIN" in material:
        return serialization.load_pem_public_key(material)
    if len(material) == 32:
        return Ed25519PublicKey.from_public_bytes(material)
    return Ed25519PublicKey.from_public_bytes(_b64d(material.decode("ascii")))


class TokenInvalid(Exception):
    """The token is absent, malformed, unsigned by us, or for another install."""


def sign(payload: TokenPayload, private_key_pem: bytes) -> str:
    """Server side only. Never called in the customer application."""
    from cryptography.hazmat.primitives import serialization
    key = serialization.load_pem_private_key(private_key_pem, password=None)
    body = json.dumps(payload.as_dict(), separators=(",", ":"),
                      sort_keys=True).encode("utf-8")
    return f"{_b64e(body)}.{_b64e(key.sign(body))}"


def verify(token: str, public_key_pem: bytes,
           install: str = "") -> TokenPayload:
    """Parse and check a token. Raises TokenInvalid for anything wrong."""
    from cryptography.exceptions import InvalidSignature
    from cryptography.hazmat.primitives import serialization

    if not token or "." not in token:
        raise TokenInvalid("no token")
    body_b64, sig_b64 = token.split(".", 1)
    try:
        body, signature = _b64d(body_b64), _b64d(sig_b64)
    except Exception as exc:
        raise TokenInvalid("token is not readable") from exc

    try:
        key = load_public_key(public_key_pem)
        key.verify(signature, body)
    except InvalidSignature as exc:
        raise TokenInvalid("token was not signed by us") from exc
    except Exception as exc:
        raise TokenInvalid("token could not be checked") from exc

    try:
        data = json.loads(body.decode("utf-8"))
    except Exception as exc:
        raise TokenInvalid("token contents are not readable") from exc

    if int(data.get("v", 0)) != TOKEN_VERSION:
        raise TokenInvalid("token version is not one this build understands")

    payload = TokenPayload(
        status=str(data.get("status", "")),
        expires=data.get("expires"),
        plan=str(data.get("plan", "")),
        install=str(data.get("install", "")),
        key_tail=str(data.get("key_tail", "")),
        issued=float(data.get("issued") or 0.0),
        grace_days=int(data.get("grace_days") or DEFAULT_GRACE_DAYS),
        max_version=data.get("max_version"),
    )

    # A token minted for one install must not unlock another. This is the
    # cheap half of seat enforcement; the server owns the expensive half.
    if install and payload.install and payload.install != install:
        raise TokenInvalid("token belongs to a different installation")
    return payload


def is_within_grace(payload: TokenPayload, now: Optional[float] = None) -> bool:
    """May a cached token still be trusted without reaching the server?"""
    return (now or time.time()) <= payload.grace_expires
